[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["toadslop <bnheise@gmail.com"]
readme = "./README.md"
description = "Frontend for example Rust fullstack application.."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"
yew = "0.19.3"

[lib]
crate-type = ["rlib", "cdylib"]