version: "3.9"
services:
  database:
    env_file:
      - docker.env
    image: "postgres:14.6"
    restart: always
    # environment:
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_DB=${DB_NAME}
    #   - PGDATA=./database/data/
    ports:
      - "5434:5432"
  backend:
    env_file:
      - docker.env
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    ports: 
      - "8080:8080"
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - database